import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ArrowLeft, CheckCircle2, ChevronRight, Heart, LockKeyhole, ReceiptText, Search, ShieldCheck, Tag, WalletCards } from "lucide-react";
import api from "../../services/api";
import { addToCart } from "./cart";
import "./CustomerAccountPages.css";

type ApiError = { response?: { data?: { detail?: string } } };
const messageFor = (error: unknown) => (error as ApiError).response?.data?.detail || "Something went wrong. Please try again.";
const money = (value: unknown) => `₦${Number(value || 0).toLocaleString("en-NG", { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;

type Transaction = { id: string; amount: number; type: string; status: string; description?: string; payment_method?: string; payment_reference?: string; created_at?: string; order_id?: string };
export function CustomerWallet() {
  const [balance, setBalance] = useState(0); const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [amount, setAmount] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [wallet, history] = await Promise.all([api.get<{ balance: number }>("/payments/wallet/balance"), api.get<Transaction[]>("/payments/wallet/transactions")]); setBalance(Number(wallet.data.balance || 0)); setTransactions(history.data || []); } catch (err) { setError(messageFor(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function fund(event: FormEvent) { event.preventDefault(); const value = Number(amount); if (!Number.isFinite(value) || value < 100) { setError("Enter at least ₦100."); return; } setBusy(true); setError(""); try { const user = JSON.parse(localStorage.getItem("userData") || "{}"); const { data } = await api.post<{ authorization_url: string }>("/payments/wallet/initialize", { amount: value, customer_email: user.email, callback_url: `${window.location.origin}/customer/wallet/verify` }); window.location.assign(data.authorization_url); } catch (err) { setError(messageFor(err)); setBusy(false); } }
  return <div className="pepi-customer-tool"><div className="pepi-page-heading"><div><h2>Your wallet</h2><p>Add money securely and use it for faster checkout.</p></div></div>{error && <p className="pepi-form-error" role="alert">{error}</p>}<section className="pepi-wallet-card"><span>Available balance</span><strong>{loading ? "Loading" : money(balance)}</strong><small>Protected payments through Paystack</small></section><form className="pepi-panel pepi-fund-form" onSubmit={fund}><div><h3>Add money</h3><p>Choose an amount or enter your own.</p></div><label>Amount<div className="pepi-money-input"><span>₦</span><input inputMode="decimal" min="100" max="5000000" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0" aria-label="Top-up amount" /></div></label><div className="pepi-preset-row">{[1000, 2000, 5000, 10000].map(value => <button type="button" key={value} onClick={() => setAmount(String(value))}>+{money(value)}</button>)}</div><button className="pepi-primary" disabled={busy}>{busy ? "Opening payment" : "Continue to secure payment"}</button></form><section className="pepi-section"><div className="pepi-section-heading"><div><h2>Recent activity</h2><p>Your wallet credits and payments</p></div><button className="pepi-secondary-action" onClick={() => void load()}>Refresh</button></div><div className="pepi-panel pepi-transaction-list">{transactions.length ? transactions.map(item => <article key={item.id}><span className={item.type === "credit" ? "credit" : "debit"}><ReceiptText size={18}/></span><div><strong>{item.description || (item.type === "credit" ? "Wallet top-up" : "Order payment")}</strong><small>{item.created_at ? new Date(item.created_at).toLocaleString("en-NG") : ""} · {item.status}</small></div><b className={item.type === "credit" ? "credit" : ""}>{item.type === "credit" ? "+" : "-"}{money(item.amount)}</b></article>) : !loading && <p>No wallet activity yet.</p>}</div></section></div>;
}

export function WalletVerify() {
  const [params] = useSearchParams(); const reference = params.get("reference") || params.get("trxref") || ""; const [state, setState] = useState<"checking"|"success"|"failed">("checking"); const [detail, setDetail] = useState("");
  useEffect(() => { if (!reference) { setDetail("The payment reference is missing."); setState("failed"); return; } api.post(`/payments/wallet/verify/${encodeURIComponent(reference)}`).then(({ data }) => { setDetail(`Your new balance is ${money(data.balance)}.`); setState(data.status === "success" ? "success" : "failed"); }).catch(error => { setDetail(messageFor(error)); setState("failed"); }); }, [reference]);
  return <div className="pepi-result-card pepi-panel">{state === "checking" ? <><span className="pepi-result-spinner"/><h2>Confirming your payment</h2><p>Please keep this page open.</p></> : state === "success" ? <><CheckCircle2/><h2>Wallet funded</h2><p>{detail}</p><Link className="pepi-primary" to="/customer/wallet">Return to wallet</Link></> : <><WalletCards/><h2>We could not confirm the payment</h2><p>{detail}</p><Link className="pepi-primary" to="/customer/wallet">Try again</Link></>}</div>;
}

export function CustomerOnboarding() {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ firstname: "", lastname: "", phone: "", address: "", city: "", state: "Lagos", addressName: "Home", instructions: "" });
  useEffect(() => { api.get("/auth/profile").then(({ data }) => setForm(current => ({ ...current, firstname: data.firstname || "", lastname: data.lastname || "", phone: data.phone || "", address: data.address || "", city: data.city || "", state: data.state || "Lagos" }))).catch(() => undefined); }, []);
  async function finish(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await api.patch("/user/profile", { firstname: form.firstname.trim(), lastname: form.lastname.trim(), phone: form.phone.trim(), address: form.address.trim(), city: form.city.trim(), state: form.state.trim(), profile_completed: true, onboarding_completed: true }); const addresses = await api.get<unknown[]>("/customer/addresses"); if (!addresses.data.length && form.address.trim()) await api.post("/customer/addresses", { address: form.address.trim(), address_name: form.addressName.trim() || "Home", delivery_instructions: form.instructions.trim() || null, is_default: true }); const stored = JSON.parse(localStorage.getItem("userData") || "{}"); localStorage.setItem("userData", JSON.stringify({ ...stored, ...form, profile_completed: true, onboarding_completed: true })); navigate("/customer/home", { replace: true }); window.location.reload(); } catch (err) { setError(messageFor(err)); setBusy(false); } }
  return <div className="pepi-onboarding"><section><div className="pepi-onboarding-progress"><span>Step {step} of 2</span><div><i className="active"/><i className={step === 2 ? "active" : ""}/></div></div>{step === 1 ? <form className="pepi-panel pepi-checkout-form" onSubmit={event => { event.preventDefault(); setStep(2); }}><h2>Let’s get your account ready</h2><p>We use these details for orders and delivery updates.</p><label>First name<input required value={form.firstname} onChange={event => setForm({ ...form, firstname: event.target.value })}/></label><label>Last name<input required value={form.lastname} onChange={event => setForm({ ...form, lastname: event.target.value })}/></label><label>Phone number<input required inputMode="tel" value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })}/></label><button className="pepi-primary">Continue</button></form> : <form className="pepi-panel pepi-checkout-form" onSubmit={finish}><button type="button" className="pepi-inline-back" onClick={() => setStep(1)}><ArrowLeft size={16}/> Back</button><h2>Where should we deliver?</h2><p>You can add more addresses later.</p><label>Address name<input value={form.addressName} onChange={event => setForm({ ...form, addressName: event.target.value })}/></label><label>Full delivery address<textarea required value={form.address} onChange={event => setForm({ ...form, address: event.target.value })}/></label><label>City<input required value={form.city} onChange={event => setForm({ ...form, city: event.target.value })}/></label><label>State<input required value={form.state} onChange={event => setForm({ ...form, state: event.target.value })}/></label><label>Delivery instructions<textarea value={form.instructions} onChange={event => setForm({ ...form, instructions: event.target.value })} placeholder="Gate, landmark, or drop-off guidance"/></label>{error && <p className="pepi-form-error">{error}</p>}<button className="pepi-primary" disabled={busy}>{busy ? "Saving" : "Start ordering"}</button></form>}</section><aside><ShieldCheck/><h2>Good food starts with a smooth delivery.</h2><p>Set your contact details and primary address once. Checkout will be faster every time.</p></aside></div>;
}

type Meal = { id: string; vendor_id: string; name: string; price: number; image_url?: string; description?: string; category?: string; vendor?: { business_name?: string } };
function MealCollection({ offers = false }: { offers?: boolean }) {
  const endpoint = offers ? "/customer/offers" : "/customer/meal-favorites"; const [items, setItems] = useState<Meal[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState("");
  const load = useCallback(() => { setLoading(true); api.get<Meal[]>(endpoint).then(({ data }) => { setItems(data); setError(""); }).catch(err => setError(messageFor(err))).finally(() => setLoading(false)); }, [endpoint]); useEffect(load, [load]);
  const shown = useMemo(() => items.filter(item => `${item.name} ${item.category || ""} ${item.vendor?.business_name || ""}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  async function remove(id: string) { try { await api.delete(`/customer/meal-favorites/${id}`); await load(); } catch (err) { setError(messageFor(err)); } }
  return <><div className="pepi-page-heading"><div><h2>{offers ? "Offers for you" : "Favorite meals"}</h2><p>{offers ? "Fresh deals from kitchens near you." : "Meals you saved for another day."}</p></div></div><label className="pepi-search-label"><Search size={18}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search this list"/></label>{loading && <p role="status">Loading meals</p>}{error && <p className="pepi-form-error">{error}</p>}<div className="pepi-product-grid">{shown.map(item => <article className="pepi-product-card" key={item.id}><div className="pepi-product-image">{item.image_url ? <img src={item.image_url} alt={item.name}/> : <Tag/>}</div><div><small>{item.vendor?.business_name || item.category}</small><h3>{item.name}</h3><p>{item.description}</p><strong>{money(item.price)}</strong><div className="pepi-card-actions"><button className="pepi-primary" onClick={() => addToCart({ id: item.id, originalId: item.id, vendor_id: item.vendor_id, vendor_name: item.vendor?.business_name, name: item.name, price: Number(item.price), quantity: 1, image_url: item.image_url })}>Add to cart</button>{!offers && <button aria-label="Remove favorite" onClick={() => void remove(item.id)}><Heart size={17} fill="currentColor"/></button>}</div></div></article>)}</div>{!loading && !shown.length && <div className="pepi-panel">{offers ? "No active offers right now." : "You have not saved any meals yet."}</div>}</>;
}
export function CustomerFavorites() { return <MealCollection/>; }
export function CustomerOffers() { return <MealCollection offers/>; }

export function CustomerPassword() {
  const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (next !== confirm) { setMessage("New passwords do not match."); return; } setBusy(true); setMessage(""); try { await api.post("/user/change-password", { current_password: current, new_password: next }); setCurrent(""); setNext(""); setConfirm(""); setMessage("Password changed successfully."); } catch (err) { setMessage(messageFor(err)); } finally { setBusy(false); } }
  return <><div className="pepi-page-heading"><div><h2>Change password</h2><p>Use a unique password with at least eight characters.</p></div></div><form className="pepi-panel pepi-checkout-form" onSubmit={submit}><LockKeyhole/><label>Current password<input type="password" required value={current} onChange={event => setCurrent(event.target.value)}/></label><label>New password<input type="password" minLength={8} required value={next} onChange={event => setNext(event.target.value)}/></label><label>Confirm new password<input type="password" minLength={8} required value={confirm} onChange={event => setConfirm(event.target.value)}/></label><button className="pepi-primary" disabled={busy}>{busy ? "Updating" : "Update password"}</button>{message && <p role="status" className={message.includes("successfully") ? "pepi-inline-notice" : "pepi-form-error"}>{message}</p>}</form></>;
}

const faqs = [
  ["How do I track my order?", "Open Orders and select an active order. You will see its timeline and the rider’s live location after pickup is assigned."],
  ["Can I schedule an order?", "Yes. Choose a future date and time while selecting meal options or during checkout."],
  ["How does wallet funding work?", "Open Wallet, choose an amount, and complete the secure Paystack payment. Your balance updates after verification."],
  ["Can I change my delivery address?", "You can save several addresses and choose one during checkout. Changing an address does not affect an order already in progress."],
  ["What if an item is missing?", "Open Support, choose missing item, and include the order details. The support team can continue the conversation in your ticket."],
];
export function CustomerFaq() { const [open, setOpen] = useState(0); return <><div className="pepi-page-heading"><div><h2>Frequently asked questions</h2><p>Quick answers for ordering, delivery, and payments.</p></div></div><div className="pepi-faq-list">{faqs.map(([question, answer], index) => <button key={question} onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}><span><strong>{question}</strong>{open === index && <small>{answer}</small>}</span><ChevronRight className={open === index ? "open" : ""}/></button>)}</div><div className="pepi-panel">Still need help? <Link to="/customer/support">Contact support</Link>.</div></>; }

export function CustomerPreferences() {
  const storageKey = "pepiCustomerPreferences"; const [prefs, setPrefs] = useState(() => { try { return { orderUpdates: true, offers: true, email: true, location: true, ...JSON.parse(localStorage.getItem(storageKey) || "{}") }; } catch { return { orderUpdates: true, offers: true, email: true, location: true }; } }); const [saved, setSaved] = useState(false);
  const rows: [("orderUpdates" | "offers" | "email" | "location"), string, string][] = [["orderUpdates", "Order updates", "Preparation, rider, and delivery notifications"], ["offers", "Offers and recommendations", "Relevant deals from nearby kitchens"], ["email", "Email receipts", "Payment and order confirmations"], ["location", "Location assistance", "Use your location to improve nearby results"]];
  function save() { localStorage.setItem(storageKey, JSON.stringify(prefs)); setSaved(true); window.setTimeout(() => setSaved(false), 1800); }
  return <><div className="pepi-page-heading"><div><h2>Preferences</h2><p>Choose how Pepi supports your orders.</p></div></div><div className="pepi-panel pepi-setting-list">{rows.map(([key, title, text]) => <label key={key}><span><strong>{title}</strong><small>{text}</small></span><input type="checkbox" checked={prefs[key]} onChange={event => setPrefs({ ...prefs, [key]: event.target.checked })}/></label>)}</div><button className="pepi-primary" onClick={save}>{saved ? "Saved" : "Save preferences"}</button></>;
}

export function CustomerOrderRoute() { const { id = "" } = useParams(); return <CustomerOrderRedirect id={id}/>; }
function CustomerOrderRedirect({ id }: { id: string }) { const navigate = useNavigate(); useEffect(() => { navigate(`/customer/orders?orderId=${encodeURIComponent(id)}`, { replace: true }); }, [id, navigate]); return <p role="status">Opening order</p>; }
