import { useMemo, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, Eye, EyeOff, LockKeyhole, Mail, Phone, UserRound } from "lucide-react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import api from "../../services/api";
import { backendAuthService } from "../../services/backendAuthService";
import { roleHome, type PepiRole } from "./roleRouting";
import { AuthField, AuthShell } from "./AuthShell";

const errorText = (error: unknown) => (error as { response?: { data?: { detail?: string } }; message?: string }).response?.data?.detail || (error as Error).message || "Please try again.";
type Role = Exclude<PepiRole, "admin">;
const roles: Record<Role, [string, string]> = { customer: ["Order food", "Discover kitchens and follow every delivery."], vendor: ["Grow a kitchen", "Manage your menu, orders, and earnings."], rider: ["Make deliveries", "Find delivery work and track what you earn."] };

export function Registration() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const requested = params.get("role");
  const [role, setRole] = useState<Role>(requested === "vendor" || requested === "rider" ? requested : "customer"); const [step, setStep] = useState(1);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [first, setFirst] = useState(""); const [last, setLast] = useState(""); const [phone, setPhone] = useState(""); const [otp, setOtp] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const strength = useMemo(() => [password.length >= 8, /[A-Z]/.test(password), /[0-9]/.test(password), /[^A-Za-z0-9]/.test(password)].filter(Boolean).length, [password]);
  const next = (event: FormEvent) => { event.preventDefault(); setError(""); setStep(value => value + 1); };
  async function register(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await backendAuthService.register({ email, password, firstname: first, lastname: last, phone, user_type: role }); setStep(4); setNotice("We sent a six-digit code to your email."); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }
  async function verify(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = await backendAuthService.verifyOTP(email, otp, role); navigate(roleHome(result.user?.role || role), { replace: true }); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }
  async function resend() { setError(""); try { await api.post("/auth/send-otp", { email }); setNotice("A new code has been sent."); } catch (err) { setError(errorText(err)); } }
  const headings = [["How will you use Pepi?", "Choose the account that matches what you want to do."], ["Tell us about you", "Use the name and phone number you want connected to your account."], ["Secure your account", "Choose your sign-in details. You can change them later."], ["Verify your email", `Enter the code sent to ${email}.`]];
  return <AuthShell title={headings[step - 1][0]} copy={headings[step - 1][1]} step={step}>{notice && <p className="auth-notice">{notice}</p>}{error && <p role="alert" className="auth-error">{error}</p>}
    {step === 1 && <form className="auth-form" onSubmit={next}><div className="role-choices">{(Object.keys(roles) as Role[]).map(value => <button type="button" className={`role-choice ${role === value ? "selected" : ""}`} onClick={() => setRole(value)} key={value}><strong>{roles[value][0]}</strong><i/><p>{roles[value][1]}</p></button>)}</div><button className="auth-primary">Continue <ArrowRight/></button></form>}
    {step === 2 && <form className="auth-form" onSubmit={next}><div className="auth-grid"><AuthField label="First name"><div className="auth-control"><UserRound/><input autoComplete="given-name" value={first} onChange={e => setFirst(e.target.value)} required/></div></AuthField><AuthField label="Last name"><div className="auth-control"><UserRound/><input autoComplete="family-name" value={last} onChange={e => setLast(e.target.value)} required/></div></AuthField></div><AuthField label="Phone number" hint="Include your country code if you are outside Nigeria."><div className="auth-control"><Phone/><input type="tel" autoComplete="tel" value={phone} onChange={e => setPhone(e.target.value)} placeholder="0800 000 0000" required/></div></AuthField><div className="auth-actions"><button type="button" className="auth-secondary" onClick={() => setStep(1)}><ArrowLeft/> Back</button><button className="auth-primary">Continue <ArrowRight/></button></div></form>}
    {step === 3 && <form className="auth-form" onSubmit={register}><AuthField label="Email address"><div className="auth-control"><Mail/><input type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required/></div></AuthField><AuthField label="Password" hint="Use at least 8 characters. A number and symbol make it stronger."><div className="auth-control"><LockKeyhole/><input type={show ? "text" : "password"} autoComplete="new-password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} required/><button type="button" aria-label={show ? "Hide password" : "Show password"} onClick={() => setShow(!show)}>{show ? <EyeOff/> : <Eye/>}</button></div><div className="password-meter">{[1,2,3,4].map(value => <i className={value <= strength ? "on" : ""} key={value}/>)}</div></AuthField><p className="auth-foot" style={{ margin: 0 }}>By continuing, you agree to the <Link to="/terms">Terms</Link> and <Link to="/privacy">Privacy Policy</Link>.</p><div className="auth-actions"><button type="button" className="auth-secondary" onClick={() => setStep(2)}><ArrowLeft/> Back</button><button className="auth-primary" disabled={busy}>{busy ? "Creating account..." : "Create account"}<ArrowRight/></button></div></form>}
    {step === 4 && <form className="auth-form" onSubmit={verify}><AuthField label="Verification code"><div className="auth-control"><input className="otp-input" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, ""))} placeholder="000000" required/></div></AuthField><button className="auth-primary" disabled={busy}>{busy ? "Checking code..." : "Verify email"}<ArrowRight/></button><button className="auth-secondary" type="button" onClick={() => void resend()}>Send a new code</button></form>}
    <p className="auth-foot">Already have an account? <Link to={`/signin?role=${role}`}>Sign in</Link></p>
  </AuthShell>;
}

export function PasswordReset() {
  const [email, setEmail] = useState(""); const [otp, setOtp] = useState(""); const [password, setPassword] = useState(""); const [stage, setStage] = useState<"email"|"reset"|"done">("email"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function send(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await api.post("/auth/forgot-password", { email }); setStage("reset"); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }
  async function reset(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await api.post("/auth/reset-password", { email, otp_code: otp, new_password: password }); setStage("done"); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }
  return <AuthShell title={stage === "done" ? "Password updated" : "Reset your password"} copy={stage === "email" ? "Enter your email and we will send a reset code." : stage === "reset" ? `Use the code sent to ${email} and choose a new password.` : "You can now sign in with your new password."}>{error && <p className="auth-error">{error}</p>}{stage === "email" ? <form className="auth-form" onSubmit={send}><AuthField label="Email address"><div className="auth-control"><Mail/><input type="email" value={email} onChange={e => setEmail(e.target.value)} required/></div></AuthField><button className="auth-primary" disabled={busy}>Send reset code <ArrowRight/></button></form> : stage === "reset" ? <form className="auth-form" onSubmit={reset}><AuthField label="Reset code"><div className="auth-control"><input className="otp-input" inputMode="numeric" value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, ""))} required/></div></AuthField><AuthField label="New password"><div className="auth-control"><LockKeyhole/><input type="password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} required/></div></AuthField><button className="auth-primary" disabled={busy}>Reset password</button></form> : <Link className="auth-primary" to="/signin">Sign in <ArrowRight/></Link>}</AuthShell>;
}
