/* eslint-disable @typescript-eslint/no-explicit-any */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { Bike, ChevronRight, Compass, ExternalLink, LocateFixed, MapPin, MessageCircle, Navigation, Phone, RefreshCw, Store, UserRound } from "lucide-react";
import api from "../../services/api";
import { animateGoogleMarker, loadGoogleMaps } from "../../services/googleMaps";
import "./RiderMapPage.css";

type Coordinate = { lat: number; lng: number };
type RiderOrder = { id: string; status: string; restaurant_name?: string; customer_name?: string; customer_phone?: string; user_id?: string; vendor_user_id?: string; vendor_phone?: string; delivery_address?: string; delivery_latitude?: number | string; delivery_longitude?: number | string; vendor_latitude?: number | string; vendor_longitude?: number | string; created_at?: string; updated_at?: string; vendor?: { business_name?: string; latitude?: number | string; longitude?: number | string; phone?: string; user_id?: string; logo_url?: string }; user?: { profile_image?: string } };
type RouteInfo = { distanceKm: number; durationMinutes: number | null; estimated: boolean };

const numeric = (value: unknown) => { const result = Number(value); return value === "" || value == null || !Number.isFinite(result) ? null : result; };
const point = (lat: unknown, lng: unknown): Coordinate | null => { const latitude = numeric(lat); const longitude = numeric(lng); return latitude == null || longitude == null ? null : { lat: latitude, lng: longitude }; };
const distanceKm = (a: Coordinate, b: Coordinate) => { const rad = (value: number) => value * Math.PI / 180; const dLat = rad(b.lat - a.lat); const dLng = rad(b.lng - a.lng); const value = Math.sin(dLat / 2) ** 2 + Math.cos(rad(a.lat)) * Math.cos(rad(b.lat)) * Math.sin(dLng / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(value), Math.sqrt(1 - value)); };
const activePriority: Record<string, number> = { picked_up: 0, accepted: 1, preparing: 2, ready: 3, pending: 4, confirmed: 4 };

export default function RiderMapPage() {
  const [params, setParams] = useSearchParams(); const navigate = useNavigate(); const requestedId = params.get("orderId");
  const mapNode = useRef<HTMLDivElement>(null); const map = useRef<any>(null); const riderMarker = useRef<any>(null); const orderMarkers = useRef<any[]>([]); const routeRenderers = useRef<any[]>([]); const lastLocationPost = useRef(0);
  const [orders, setOrders] = useState<RiderOrder[]>([]); const [specificOrder, setSpecificOrder] = useState<RiderOrder | null>(null); const [selectedId, setSelectedId] = useState<string | null>(requestedId); const [location, setLocation] = useState<Coordinate | null>(null); const [routingLocation, setRoutingLocation] = useState<Coordinate | null>(null); const [heading, setHeading] = useState(0); const [mapReady, setMapReady] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [mapError, setMapError] = useState(""); const [route, setRoute] = useState<RouteInfo | null>(null); const [futureRoute, setFutureRoute] = useState<RouteInfo | null>(null); const [follow, setFollow] = useState(true); const [navigationMode, setNavigationMode] = useState(false); const [busy, setBusy] = useState(false);

  const loadOrders = useCallback(async () => { setLoading(true); try { const { data } = await api.get<RiderOrder[]>("/riders/orders"); const active = data.filter(order => ["accepted", "preparing", "ready", "picked_up"].includes(order.status)).sort((a, b) => (activePriority[a.status] ?? 99) - (activePriority[b.status] ?? 99) || new Date(b.updated_at || b.created_at || 0).getTime() - new Date(a.updated_at || a.created_at || 0).getTime()); setOrders(active); setSelectedId(current => current || active[0]?.id || null); setError(""); } catch (err) { setError((err as { response?: { data?: { detail?: string } } }).response?.data?.detail || "Could not load rider routes."); } finally { setLoading(false); } }, []);
  useEffect(() => { void loadOrders(); const timer = window.setInterval(() => void loadOrders(), 15000); return () => window.clearInterval(timer); }, [loadOrders]);
  useEffect(() => { if (!requestedId || orders.some(order => order.id === requestedId)) { setSpecificOrder(null); return; } api.get<RiderOrder>(`/orders/${requestedId}`).then(({ data }) => { setSpecificOrder(data); setSelectedId(data.id); }).catch(() => setError("The requested order route could not be loaded.")); }, [requestedId, orders]);
  const markerOrders = useMemo(() => specificOrder && !orders.some(order => order.id === specificOrder.id) ? [...orders, specificOrder] : orders, [orders, specificOrder]);
  const activeOrder = markerOrders.find(order => order.id === selectedId) || markerOrders[0] || null;
  const pickup = useMemo(() => activeOrder ? point(activeOrder.vendor?.latitude ?? activeOrder.vendor_latitude, activeOrder.vendor?.longitude ?? activeOrder.vendor_longitude) : null, [activeOrder]);
  const dropoff = useMemo(() => activeOrder ? point(activeOrder.delivery_latitude, activeOrder.delivery_longitude) : null, [activeOrder]);
  const destination = activeOrder?.status === "picked_up" ? dropoff : pickup;

  useEffect(() => {
    if (!navigator.geolocation) { setError("Location is unavailable in this browser."); return; }
    const watch = navigator.geolocation.watchPosition(position => { const next = { lat: position.coords.latitude, lng: position.coords.longitude }; setLocation(next); setRoutingLocation(current => !current || distanceKm(current, next) >= .05 ? next : current); if (position.coords.heading != null) setHeading(position.coords.heading); if (Date.now() - lastLocationPost.current >= 5000) { lastLocationPost.current = Date.now(); void api.post("/riders/location", { latitude: next.lat, longitude: next.lng }).catch(() => undefined); } }, () => setError("Allow precise location access to use live routing."), { enableHighAccuracy: true, maximumAge: 2000, timeout: 12000 });
    return () => navigator.geolocation.clearWatch(watch);
  }, []);

  useEffect(() => { if (!mapNode.current) return; let cancelled = false; void loadGoogleMaps().then(() => { if (cancelled || !mapNode.current) return; map.current = new window.google.maps.Map(mapNode.current, { center: { lat: 6.5244, lng: 3.3792 }, zoom: 14, mapTypeControl: false, streetViewControl: false, fullscreenControl: false, gestureHandling: "greedy", styles: [{ featureType: "poi", elementType: "labels", stylers: [{ visibility: "off" }] }] }); new window.google.maps.TrafficLayer().setMap(map.current); map.current.addListener("dragstart", () => setFollow(false)); setMapReady(true); setMapError(""); }).catch(err => setMapError(err.message || "Google Maps could not load.")); return () => { cancelled = true; }; }, []);

  useEffect(() => { if (!mapReady || !map.current || !location) return; if (!riderMarker.current) riderMarker.current = new window.google.maps.Marker({ map: map.current, position: location, title: "Your live location", icon: { path: window.google.maps.SymbolPath.FORWARD_CLOSED_ARROW, scale: 6, rotation: heading, fillColor: "#ffffff", fillOpacity: 1, strokeColor: "#2d8c1f", strokeWeight: 5 } }); else { animateGoogleMarker(riderMarker.current, location, 1500); riderMarker.current.setIcon({ path: window.google.maps.SymbolPath.FORWARD_CLOSED_ARROW, scale: 6, rotation: heading, fillColor: "#ffffff", fillOpacity: 1, strokeColor: "#2d8c1f", strokeWeight: 5 }); } if (follow && navigationMode) { map.current.panTo(location); map.current.setZoom(18); map.current.setHeading(heading); map.current.setTilt(45); } }, [location, heading, mapReady, follow, navigationMode]);

  useEffect(() => {
    if (!mapReady || !map.current) return; orderMarkers.current.forEach(marker => marker.setMap(null)); orderMarkers.current = [];
    markerOrders.forEach(order => {
      const orderPickup = point(order.vendor?.latitude ?? order.vendor_latitude, order.vendor?.longitude ?? order.vendor_longitude);
      const orderDropoff = point(order.delivery_latitude, order.delivery_longitude);
      const addMarker = (position: Coordinate, dropoffMarker: boolean) => {
        const marker = new window.google.maps.Marker({ map: map.current, position, title: dropoffMarker ? "Customer drop-off" : order.restaurant_name || order.vendor?.business_name || "Kitchen", label: { text: dropoffMarker ? "D" : "P", color: dropoffMarker ? "#ffffff" : "#1f6b14", fontWeight: "800" }, icon: { path: window.google.maps.SymbolPath.CIRCLE, scale: order.id === activeOrder?.id ? 17 : 13, fillColor: dropoffMarker ? "#2d8c1f" : "#ffd93d", fillOpacity: 1, strokeColor: "#ffffff", strokeWeight: 3 } });
        marker.addListener("click", () => { setSelectedId(order.id); setParams({ orderId: order.id }); setNavigationMode(false); setFollow(true); });
        orderMarkers.current.push(marker);
      };
      if (order.status !== "picked_up" && orderPickup) addMarker(orderPickup, false);
      if (orderDropoff) addMarker(orderDropoff, true);
    });
  }, [markerOrders, activeOrder?.id, mapReady, setParams]);

  useEffect(() => {
    if (!mapReady || !map.current) return; routeRenderers.current.forEach(renderer => renderer.setMap(null)); routeRenderers.current = []; setRoute(null); setFutureRoute(null);
    if (!routingLocation || !destination) return; const service = new window.google.maps.DirectionsService(); const render = (origin: Coordinate, target: Coordinate, primary: boolean) => service.route({ origin, destination: target, travelMode: window.google.maps.TravelMode.DRIVING }).then((result: any) => { const renderer = new window.google.maps.DirectionsRenderer({ map: map.current, suppressMarkers: true, preserveViewport: true, polylineOptions: { strokeColor: primary ? "#2d8c1f" : "#98a29a", strokeWeight: primary ? 6 : 3, strokeOpacity: primary ? .95 : .7 } }); renderer.setDirections(result); routeRenderers.current.push(renderer); const leg = result.routes[0]?.legs[0]; const info = { distanceKm: Number(leg?.distance?.value || 0) / 1000, durationMinutes: Number(leg?.duration?.value || 0) / 60, estimated: false }; if (primary) setRoute(info); else setFutureRoute(info); }).catch(() => { if (primary) setRoute({ distanceKm: distanceKm(origin, target), durationMinutes: null, estimated: true }); });
    void render(routingLocation, destination, true); if (activeOrder?.status !== "picked_up" && pickup && dropoff) void render(pickup, dropoff, false);
    if (!navigationMode) { const bounds = new window.google.maps.LatLngBounds(); bounds.extend(routingLocation); if (pickup) bounds.extend(pickup); if (dropoff) bounds.extend(dropoff); map.current.fitBounds(bounds, 70); }
  }, [activeOrder?.id, activeOrder?.status, destination, pickup, dropoff, routingLocation, mapReady, navigationMode]);

  const selectOrder = (id: string) => { setSelectedId(id); setParams({ orderId: id }); setNavigationMode(false); setFollow(true); };
  const recenter = () => { if (!map.current || !location) return; setFollow(true); if (destination) { const bounds = new window.google.maps.LatLngBounds(); bounds.extend(location); bounds.extend(destination); map.current.fitBounds(bounds, 80); } else { map.current.panTo(location); map.current.setZoom(16); } };
  const externalDirections = () => { if (destination) window.open(`https://www.google.com/maps/dir/?api=1&destination=${destination.lat},${destination.lng}&travelmode=driving`, "_blank", "noopener,noreferrer"); };
  const contactPhone = activeOrder?.status === "picked_up" ? activeOrder.customer_phone : activeOrder?.vendor?.phone || activeOrder?.vendor_phone;
  const contactId = activeOrder?.status === "picked_up" ? activeOrder.user_id : activeOrder?.vendor?.user_id || activeOrder?.vendor_user_id;
  const accept = async () => { if (!activeOrder) return; setBusy(true); try { await api.post(`/riders/orders/${activeOrder.id}/accept`); await loadOrders(); setNavigationMode(true); } catch (err) { setError((err as { response?: { data?: { detail?: string } } }).response?.data?.detail || "This delivery could not be accepted."); } finally { setBusy(false); } };
  const legName = activeOrder?.status === "picked_up" ? "Customer drop-off" : "Kitchen pickup";

  return <div className="pepi-rider-map-page">
    <header className="pepi-map-header"><div><h2>Delivery map</h2><p>{activeOrder ? `${legName} for order #${activeOrder.id.slice(0, 6).toUpperCase()}` : "Your active deliveries and live routes"}</p></div><span className={location ? "is-live" : ""}><i/>{location ? "Location live" : "Waiting for location"}</span></header>
    {markerOrders.length > 1 && <nav className="pepi-map-order-switcher">{markerOrders.map(order => <button className={order.id === activeOrder?.id ? "active" : ""} key={order.id} onClick={() => selectOrder(order.id)}>#{order.id.slice(0, 5).toUpperCase()}<small>{order.status === "picked_up" ? "Drop-off" : "Pickup"}</small></button>)}</nav>}
    <div className="pepi-map-workspace"><div className="pepi-map-canvas-wrap"><div ref={mapNode} className="pepi-map-canvas"/>{loading && <div className="pepi-map-loading"><RefreshCw size={22}/><span>Loading routes</span></div>}{mapError && <div className="pepi-map-error">{mapError}</div>}<div className="pepi-map-controls"><button className={navigationMode ? "active" : ""} onClick={() => { setNavigationMode(current => !current); setFollow(true); }} aria-label="Toggle navigation mode"><Navigation size={19}/></button><button className={follow && !navigationMode ? "active" : ""} onClick={recenter} aria-label="Recenter map"><LocateFixed size={19}/></button></div><div className="pepi-map-legend"><span><i className="pickup"/>Pickup</span><span><i className="dropoff"/>Drop-off</span></div></div>
      <aside className="pepi-map-sheet">{activeOrder ? <><div className="pepi-map-sheet-handle"/><section className="pepi-map-eta"><span><Navigation size={20}/></span><div><small>{route?.estimated ? "Estimated distance" : route?.durationMinutes ? "Estimated arrival" : "Calculating route"}</small><strong>{route ? route.durationMinutes ? `${Math.round(route.durationMinutes)} min` : `${route.distanceKm.toFixed(1)} km` : "Please wait"}</strong>{route && <p>{route.distanceKm.toFixed(1)} km to {legName.toLowerCase()}</p>}</div></section><section className="pepi-map-destination"><span>{activeOrder.status === "picked_up" ? <UserRound size={21}/> : <Store size={21}/>}</span><div><small>{legName}</small><strong>{activeOrder.status === "picked_up" ? activeOrder.customer_name || "Customer" : activeOrder.restaurant_name || activeOrder.vendor?.business_name || "Kitchen"}</strong><p><MapPin size={12}/>{activeOrder.status === "picked_up" ? activeOrder.delivery_address : "Pickup location"}</p></div><span className={`pepi-status-badge status-${activeOrder.status}`}>{activeOrder.status.replaceAll("_", " ")}</span></section>{futureRoute && activeOrder.status !== "picked_up" && <div className="pepi-map-future"><Bike size={16}/><span>Then {futureRoute.distanceKm.toFixed(1)} km from pickup to customer</span></div>}<div className="pepi-map-contact-actions">{contactPhone && <a href={`tel:${contactPhone}`}><Phone size={18}/><span>Call</span></a>}{contactId && <button onClick={() => navigate(`/rider/chat?recipientId=${encodeURIComponent(contactId)}`)}><MessageCircle size={18}/><span>Message</span></button>}<button onClick={externalDirections} disabled={!destination}><ExternalLink size={18}/><span>Google Maps</span></button></div><div className="pepi-map-main-actions">{["pending", "ready", "confirmed"].includes(activeOrder.status) && <button className="pepi-primary" disabled={busy} onClick={() => void accept()}>{busy ? "Accepting" : "Accept delivery"}</button>}{["accepted", "preparing", "ready", "picked_up"].includes(activeOrder.status) && <button className="pepi-primary" onClick={() => navigate("/rider/deliveries")}>Manage delivery <ChevronRight size={16}/></button>}<button onClick={() => { setNavigationMode(current => !current); setFollow(true); }}><Compass size={17}/>{navigationMode ? "Route overview" : "Start navigation"}</button></div></> : <div className="pepi-map-empty"><span><MapPin size={28}/></span><h3>No active route</h3><p>Accept a delivery to see its pickup, destination, and live directions here.</p><Link to="/rider/deliveries">Find deliveries <ChevronRight size={16}/></Link></div>}</aside>
    </div>{error && <div className="pepi-inline-error" role="alert">{error}<button onClick={() => setError("")}>Dismiss</button></div>}
  </div>;
}
