import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent } from "react";
import { useSearchParams } from "react-router-dom";
import { ArrowLeft, Check, CheckCheck, Copy, FileText, MessageCircle, Mic, MoreVertical, Paperclip, Pencil, Phone, Search, Send, Share2, Square, Trash2, X } from "lucide-react";
import api, { getAdminWebSocketUrl } from "../../services/api";
import { readStoredUser } from "../auth/roleRouting";
import "./RoleChat.css";

type Participant = { user_id: string; user?: { id: string; firstname?: string | null; lastname?: string | null; role?: string; phone?: string | null } };
type Conversation = { id: string; participants?: Participant[]; last_message_text?: string; last_message_time?: string; updated_at?: string; unread_count?: number };
type Message = { id: string; conversation_id: string; sender_id: string; text: string; created_at: string; updated_at?: string; is_read?: boolean; is_voice?: boolean; audio_url?: string; attachment_url?: string; attachment_type?: string; attachment_name?: string };
type SocketPayload = Partial<Message> & { type: string; data?: Partial<Message>; user_id?: string; is_typing?: boolean; status?: string };

const errorText = (error: unknown, fallback: string) => (error as { response?: { data?: { detail?: string } } }).response?.data?.detail || fallback;

export default function RoleChat() {
  const [params] = useSearchParams();
  const recipientId = params.get("recipientId"); const requestedConversation = params.get("conversationId");
  const storedUser = readStoredUser(); const userId = storedUser?.id;
  const [conversations, setConversations] = useState<Conversation[]>([]); const [activeId, setActiveId] = useState<string | null>(requestedConversation); const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(""); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [retryAction, setRetryAction] = useState<null | (() => void)>(null); const [sending, setSending] = useState(false); const [loadingMessages, setLoadingMessages] = useState(false); const [connected, setConnected] = useState(false); const [typing, setTyping] = useState(false); const [otherOnline, setOtherOnline] = useState(false); const [mobileThread, setMobileThread] = useState(Boolean(requestedConversation || recipientId)); const [menuOpen, setMenuOpen] = useState(false); const [uploading, setUploading] = useState(false); const [pendingFile, setPendingFile] = useState<File | null>(null); const [pendingPreview, setPendingPreview] = useState(""); const [recording, setRecording] = useState(false); const [recordingSeconds, setRecordingSeconds] = useState(0); const [selectedMessage, setSelectedMessage] = useState<Message | null>(null); const [editingMessage, setEditingMessage] = useState<Message | null>(null);
  const socketRef = useRef<WebSocket | null>(null); const reconnectRef = useRef<number | null>(null); const pingRef = useRef<number | null>(null); const messageEndRef = useRef<HTMLDivElement>(null); const fileRef = useRef<HTMLInputElement>(null); const activeRef = useRef<string | null>(activeId); const conversationsRef = useRef<Conversation[]>(conversations); const recorderRef = useRef<MediaRecorder | null>(null); const recordingStreamRef = useRef<MediaStream | null>(null); const audioChunksRef = useRef<Blob[]>([]); const recordingTimerRef = useRef<number | null>(null);
  activeRef.current = activeId;
  conversationsRef.current = conversations;

  const loadConversations = useCallback(async () => { try { const { data } = await api.get<Conversation[]>("/chat/conversations"); setConversations(data.sort((a, b) => new Date(b.last_message_time || b.updated_at || 0).getTime() - new Date(a.last_message_time || a.updated_at || 0).getTime())); setError(""); } catch (err) { setError(errorText(err, "Could not load messages.")); } }, []);
  const loadMessages = useCallback(async (conversationId: string, quiet = false) => { if (!quiet) setLoadingMessages(true); try { const { data } = await api.get<Message[]>(`/chat/messages/${conversationId}`); setMessages(data); await api.post(`/chat/conversations/${conversationId}/read`); setConversations(current => current.map(item => item.id === conversationId ? { ...item, unread_count: 0 } : item)); } catch (err) { setError(errorText(err, "Could not load this conversation.")); } finally { if (!quiet) setLoadingMessages(false); } }, []);

  useEffect(() => { void loadConversations(); }, [loadConversations]);
  useEffect(() => { if (!recipientId || !userId) return; let mounted = true; api.post<Conversation>("/chat/get-or-create", { type: "direct", participant_ids: [recipientId], chat_metadata: "" }).then(({ data }) => { if (mounted) { setActiveId(data.id); setMobileThread(true); void loadConversations(); } }).catch(err => { if (mounted) setError(errorText(err, "Could not open this conversation.")); }); return () => { mounted = false; }; }, [recipientId, userId, loadConversations]);
  useEffect(() => { if (activeId) { void loadMessages(activeId); window.setTimeout(() => messageEndRef.current?.scrollIntoView({ block: "end" }), 100); } else setMessages([]); }, [activeId, loadMessages]);

  useEffect(() => {
    const token = localStorage.getItem("authToken"); if (!token) return;
    let stopped = false; let attempt = 0;
    const connect = () => {
      if (stopped) return; const socket = new WebSocket(`${getAdminWebSocketUrl()}?token=${encodeURIComponent(token)}`); socketRef.current = socket;
      socket.onopen = () => { attempt = 0; setConnected(true); pingRef.current = window.setInterval(() => socket.readyState === WebSocket.OPEN && socket.send(JSON.stringify({ type: "ping" })), 25000); };
      socket.onmessage = event => { try { const raw = JSON.parse(event.data) as SocketPayload; const payload = { ...(raw.data || {}), ...raw }; if (raw.type === "chat_message" && payload.conversation_id) { const incoming = payload as Message; if (payload.conversation_id === activeRef.current) { setMessages(current => current.some(item => item.id === incoming.id) ? current : [...current, incoming]); void api.post(`/chat/conversations/${payload.conversation_id}/read`); window.setTimeout(() => messageEndRef.current?.scrollIntoView({ behavior: "smooth" }), 40); } void loadConversations(); } if (raw.type === "message_read" && raw.conversation_id === activeRef.current) setMessages(current => current.map(item => item.sender_id === userId ? { ...item, is_read: true } : item)); if (raw.type === "typing" && raw.conversation_id === activeRef.current && raw.user_id !== userId) setTyping(Boolean(raw.is_typing)); if (raw.type === "user_status" && raw.user_id === otherUserId(conversationsRef.current.find(item => item.id === activeRef.current), userId)) setOtherOnline(raw.status === "online"); } catch { /* ignore malformed socket messages */ } };
      socket.onclose = () => { setConnected(false); if (pingRef.current) window.clearInterval(pingRef.current); if (!stopped) { attempt += 1; reconnectRef.current = window.setTimeout(connect, Math.min(30000, 1000 * 2 ** attempt)); } };
      socket.onerror = () => socket.close();
    };
    connect(); return () => { stopped = true; if (pingRef.current) window.clearInterval(pingRef.current); if (reconnectRef.current) window.clearTimeout(reconnectRef.current); socketRef.current?.close(); };
  }, [loadConversations, userId]);

  useEffect(() => { if (!activeId || !userId || socketRef.current?.readyState !== WebSocket.OPEN) return; const timer = window.setTimeout(() => socketRef.current?.send(JSON.stringify({ type: "typing", conversation_id: activeId, user_id: userId, is_typing: Boolean(text.trim()) })), 350); return () => window.clearTimeout(timer); }, [text, activeId, userId]);
  useEffect(() => () => { recordingStreamRef.current?.getTracks().forEach(track => track.stop()); if (pendingPreview) URL.revokeObjectURL(pendingPreview); }, [pendingPreview]);

  async function send(event: FormEvent, supplied?: { url: string; name: string; type: string }) { event.preventDefault(); if (!activeId || !userId || (!text.trim() && !supplied && !pendingFile)) return; const body = text.trim(); if (editingMessage) { if (!body) return; setSending(true); setError(""); try { const { data } = await api.patch<Message>(`/chat/messages/${editingMessage.id}`, null, { params: { text: body } }); setMessages(current => current.map(item => item.id === data.id ? data : item)); setEditingMessage(null); setText(""); } catch (err) { setError(errorText(err, "Could not update this message.")); } finally { setSending(false); } return; } const fileToUpload = pendingFile; setSending(true); setError(""); setRetryAction(null); let attachment = supplied; let optimisticId = ""; try { if (fileToUpload && !attachment) { setUploading(true); const form = new FormData(); form.append("file", fileToUpload, fileToUpload.name); const type = fileToUpload.type.startsWith("image/") ? "image" : fileToUpload.type.startsWith("video/") ? "video" : "document"; const { data } = await api.post<{ url: string; filename?: string }>(`/chat/upload-attachment?type=${type}`, form); attachment = { url: data.url, name: data.filename || fileToUpload.name, type }; } optimisticId = `sending-${Date.now()}`; const optimistic: Message = { id: optimisticId, conversation_id: activeId, sender_id: userId, text: body, created_at: new Date().toISOString(), is_voice: attachment?.type === "audio", audio_url: attachment?.type === "audio" ? attachment.url : undefined, attachment_url: attachment?.type === "audio" ? undefined : attachment?.url, attachment_name: attachment?.name, attachment_type: attachment?.type }; setMessages(current => [...current, optimistic]); const { data } = await api.post<Message>("/chat/messages", { conversation_id: activeId, text: body || (attachment?.type === "audio" ? "Voice note" : attachment?.name || "Attachment"), is_voice: attachment?.type === "audio", audio_url: attachment?.type === "audio" ? attachment.url : undefined, attachment_url: attachment?.type === "audio" ? undefined : attachment?.url, attachment_name: attachment?.name, attachment_type: attachment?.type }); setMessages(current => current.map(item => item.id === optimisticId ? data : item)); setText(""); setPendingFile(null); if (pendingPreview) URL.revokeObjectURL(pendingPreview); setPendingPreview(""); void loadConversations(); } catch (err) { if (optimisticId) setMessages(current => current.filter(item => item.id !== optimisticId)); setError(errorText(err, fileToUpload ? "The attachment could not be uploaded." : "Could not send your message.")); setRetryAction(() => () => void send({ preventDefault() {} } as FormEvent, supplied)); } finally { setSending(false); setUploading(false); } }
  function chooseAttachment(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (pendingPreview) URL.revokeObjectURL(pendingPreview); setPendingFile(file); setPendingPreview(file.type.startsWith("image/") || file.type.startsWith("video/") ? URL.createObjectURL(file) : ""); event.target.value = ""; }
  async function uploadVoice(file: File) { setUploading(true); setError(""); setRetryAction(null); try { const form = new FormData(); form.append("file", file, file.name); const { data } = await api.post<{ url: string }>("/chat/upload-audio", form); await send({ preventDefault() {} } as FormEvent, { url: data.url, name: "Voice note", type: "audio" }); } catch (err) { setError(errorText(err, "Could not upload the voice note.")); setRetryAction(() => () => void uploadVoice(file)); setUploading(false); } }
  async function toggleRecording() { if (recording) { recorderRef.current?.stop(); return; } try { if (!window.MediaRecorder) throw new Error("unsupported"); const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); recordingStreamRef.current = stream; audioChunksRef.current = []; const preferred = ["audio/webm;codecs=opus", "audio/webm", "audio/mp4"].find(type => MediaRecorder.isTypeSupported(type)); const recorder = new MediaRecorder(stream, preferred ? { mimeType: preferred } : undefined); recorderRef.current = recorder; recorder.ondataavailable = event => { if (event.data.size) audioChunksRef.current.push(event.data); }; recorder.onstop = () => { setRecording(false); if (recordingTimerRef.current) window.clearInterval(recordingTimerRef.current); stream.getTracks().forEach(track => track.stop()); const mime = recorder.mimeType || preferred || "audio/webm"; const extension = mime.includes("mp4") ? "m4a" : "webm"; const blob = new Blob(audioChunksRef.current, { type: mime }); if (blob.size < 100) { setError("The recording was empty. Hold the microphone button and speak before stopping."); return; } const file = new File([blob], `voice-${Date.now()}.${extension}`, { type: mime.split(";")[0] }); void uploadVoice(file); }; recorder.start(250); setRecordingSeconds(0); recordingTimerRef.current = window.setInterval(() => setRecordingSeconds(value => value + 1), 1000); setRecording(true); } catch { setError("Microphone access is blocked or voice recording is unavailable in this browser."); setRetryAction(null); } }
  async function clearConversation() { if (!activeId || !window.confirm("Clear this conversation for your account?")) return; try { await api.post(`/chat/conversations/${activeId}/clear`); setMessages([]); setMenuOpen(false); void loadConversations(); } catch (err) { setError(errorText(err, "Could not clear the conversation.")); } }
  async function copyMessage(message: Message) { const content = message.text || message.attachment_url || message.audio_url || ""; await navigator.clipboard.writeText(content); setSelectedMessage(null); }
  async function shareMessage(message: Message) { const content = message.attachment_url || message.audio_url || message.text; try { if (navigator.share) await navigator.share({ title: "Shared message", text: message.text || undefined, url: message.attachment_url || message.audio_url || undefined }); else await navigator.clipboard.writeText(content); setSelectedMessage(null); } catch (err) { if ((err as DOMException).name !== "AbortError") setError("Could not share this message."); } }
  async function deleteMessage(message: Message, forEveryone: boolean) { try { await api.delete(`/chat/messages/${message.id}`, { params: { for_everyone: forEveryone } }); setMessages(current => current.filter(item => item.id !== message.id)); setSelectedMessage(null); void loadConversations(); } catch (err) { setError(errorText(err, "Could not delete this message.")); } }
  function beginEdit(message: Message) { setEditingMessage(message); setText(message.text); setSelectedMessage(null); window.setTimeout(() => document.querySelector<HTMLTextAreaElement>(".pepi-chat-compose textarea")?.focus(), 0); }

  const active = conversations.find(item => item.id === activeId); const activeParticipant = active?.participants?.find(person => person.user_id !== userId); const name = (conversation?: Conversation) => participantName(conversation, userId); const filtered = useMemo(() => conversations.filter(item => participantName(item, userId).toLowerCase().includes(query.toLowerCase()) || item.last_message_text?.toLowerCase().includes(query.toLowerCase())), [conversations, query, userId]);
  const dateLabel = (message: Message, index: number) => { const date = new Date(message.created_at); const previous = messages[index - 1] ? new Date(messages[index - 1].created_at) : null; if (previous?.toDateString() === date.toDateString()) return ""; const today = new Date(); return date.toDateString() === today.toDateString() ? "Today" : date.toLocaleDateString("en-NG", { dateStyle: "medium" }); };

  return <div className={`pepi-chat-page ${mobileThread ? "show-thread" : ""}`}>
    <aside className="pepi-chat-inbox"><header><div><h2>Messages</h2></div><label><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search conversations"/></label></header><div className="pepi-conversation-list">{filtered.map(conversation => <button className={activeId === conversation.id ? "active" : ""} key={conversation.id} onClick={() => { setActiveId(conversation.id); setMobileThread(true); }}><span className="pepi-chat-avatar">{name(conversation)[0]?.toUpperCase()}</span><span><strong>{name(conversation)}</strong><small>{conversation.last_message_text || "Start the conversation"}</small></span><span className="pepi-chat-meta"><time>{conversation.last_message_time ? new Date(conversation.last_message_time).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : ""}</time>{Boolean(conversation.unread_count) && <b>{conversation.unread_count}</b>}</span></button>)}{!filtered.length && <div className="pepi-chat-empty"><MessageCircle size={24}/><strong>No conversations found</strong><p>Customer and delivery conversations will appear here.</p></div>}</div></aside>
    <section className="pepi-chat-thread"><header>{active ? <><button className="pepi-chat-back" onClick={() => setMobileThread(false)}><ArrowLeft size={20}/></button><span className="pepi-chat-avatar">{name(active)[0]?.toUpperCase()}</span><div><h3>{name(active)}</h3><small>{typing ? "Typing" : otherOnline ? "Online" : connected ? "Messages are live" : "Connecting"}</small></div>{activeParticipant?.user?.phone && <a className="pepi-chat-call" href={`tel:${activeParticipant.user.phone}`} aria-label={`Call ${name(active)}`}><Phone size={18}/></a>}<button className="pepi-chat-menu-button" onClick={() => setMenuOpen(current => !current)}><MoreVertical size={19}/></button>{menuOpen && <div className="pepi-chat-menu"><button onClick={() => void clearConversation()}><Trash2 size={16}/>Clear conversation</button></div>}</> : <div className="pepi-chat-placeholder-title"><MessageCircle size={18}/><span>Select a conversation</span></div>}</header>
      {error && <div className="pepi-chat-error"><span>{error}</span>{retryAction && <button className="pepi-error-retry" onClick={retryAction}>Try again</button>}<button aria-label="Dismiss error" onClick={() => { setError(""); setRetryAction(null); }}><X size={15}/></button></div>}
      <div className="pepi-chat-messages">{loadingMessages ? <div className="pepi-chat-loading"><span/><span/><span/></div> : activeId ? messages.map((message, index) => <div key={message.id} className="pepi-message-wrap">{dateLabel(message, index) && <div className="pepi-message-date">{dateLabel(message, index)}</div>}<article className={message.sender_id === userId ? "mine" : ""}><button className="pepi-message-actions" aria-label="Message options" onClick={() => setSelectedMessage(message)}><MoreVertical size={15}/></button>{message.is_voice && message.audio_url && <audio className="pepi-voice-note" controls preload="metadata" src={message.audio_url}/>} {message.attachment_url && (message.attachment_type === "image" ? <a href={message.attachment_url} target="_blank" rel="noreferrer"><img src={message.attachment_url} alt={message.attachment_name || "Shared image"}/></a> : message.attachment_type === "video" ? <video controls preload="metadata" src={message.attachment_url}/> : <a className="pepi-message-file" href={message.attachment_url} target="_blank" rel="noreferrer"><FileText size={18}/><span>{message.attachment_name || "Attachment"}</span></a>)}{message.text && message.text !== message.attachment_name && message.text !== "Voice note" && <p>{message.text}</p>}<small>{new Date(message.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}{message.sender_id === userId && (message.is_read ? <CheckCheck className="is-read" size={13}/> : <Check size={13}/>)}</small></article></div>) : <div className="pepi-chat-welcome"><span><MessageCircle size={28}/></span><h3>Your conversations, in one place</h3><p>Select a customer or rider conversation to review messages and respond.</p></div>}<div ref={messageEndRef}/></div>
      {selectedMessage && <div className="pepi-message-sheet-backdrop" onClick={() => setSelectedMessage(null)}><div className="pepi-message-sheet" role="dialog" aria-modal="true" aria-label="Message options" onClick={event => event.stopPropagation()}><div className="pepi-sheet-handle"/><strong>Message options</strong>{selectedMessage.text && !selectedMessage.is_voice && <button onClick={() => void copyMessage(selectedMessage)}><Copy size={18}/>Copy</button>}<button onClick={() => void shareMessage(selectedMessage)}><Share2 size={18}/>Share</button>{selectedMessage.sender_id === userId && selectedMessage.text && !selectedMessage.is_voice && !selectedMessage.attachment_url && <button onClick={() => beginEdit(selectedMessage)}><Pencil size={18}/>Edit message</button>}<button onClick={() => void deleteMessage(selectedMessage, false)}><Trash2 size={18}/>Delete for me</button>{selectedMessage.sender_id === userId && <button className="danger" onClick={() => void deleteMessage(selectedMessage, true)}><Trash2 size={18}/>Delete for everyone</button>}<button className="cancel" onClick={() => setSelectedMessage(null)}>Cancel</button></div></div>}
      {activeId && <div className="pepi-compose-wrap">{editingMessage && <div className="pepi-editing-state"><Pencil size={16}/><span><strong>Editing message</strong><small>Update your text, then press send</small></span><button type="button" aria-label="Cancel editing" onClick={() => { setEditingMessage(null); setText(""); }}><X size={16}/></button></div>}{pendingFile && <div className="pepi-attachment-preview">{pendingPreview ? pendingFile.type.startsWith("video/") ? <video src={pendingPreview}/> : <img src={pendingPreview} alt="Attachment preview"/> : <FileText size={23}/>}<span><strong>{pendingFile.name}</strong><small>{Math.max(1, Math.round(pendingFile.size / 1024))} KB</small></span><button type="button" aria-label="Remove attachment" onClick={() => { if (pendingPreview) URL.revokeObjectURL(pendingPreview); setPendingFile(null); setPendingPreview(""); }}><X size={16}/></button></div>}{recording && <div className="pepi-recording-state"><i/><strong>Recording {Math.floor(recordingSeconds / 60)}:{String(recordingSeconds % 60).padStart(2,"0")}</strong><span>Press stop to send</span></div>}<form onSubmit={send} className="pepi-chat-compose"><input ref={fileRef} className="sr-only" type="file" accept="image/*,video/*,.pdf,.doc,.docx,.txt" onChange={chooseAttachment}/><button type="button" aria-label="Attach file" disabled={uploading || recording || Boolean(editingMessage)} onClick={() => fileRef.current?.click()}><Paperclip size={19}/></button><button type="button" className={recording ? "is-recording" : ""} aria-label={recording ? "Stop recording" : "Record voice note"} disabled={uploading || Boolean(editingMessage)} onClick={() => void toggleRecording()}>{recording ? <Square size={16}/> : <Mic size={19}/>}</button><label><span className="sr-only">Message</span><textarea rows={1} value={text} onChange={event => setText(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} placeholder={editingMessage ? "Edit your message" : recording ? "Recording voice note" : uploading ? "Uploading attachment" : "Write a message"}/></label><button className="pepi-send-button" aria-label={editingMessage ? "Save message" : "Send message"} disabled={sending || uploading || recording || (!text.trim() && !pendingFile)}>{editingMessage ? <Check size={18}/> : <Send size={18}/>}</button></form></div>}
    </section>
  </div>;
}

function participantName(conversation: Conversation | undefined, userId?: string) { const other = conversation?.participants?.find(person => person.user_id !== userId); const first = other?.user?.firstname || ""; const last = other?.user?.lastname || ""; return `${first} ${last}`.trim() || "Conversation"; }
function otherUserId(conversation: Conversation | undefined, userId?: string) { return conversation?.participants?.find(person => person.user_id !== userId)?.user_id; }
