import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Bike, Camera, CheckCircle2, ChevronRight, Clock3, CreditCard, FileText, LockKeyhole, MapPin, MessageCircle, Package, Phone, Shield, Store, Trash2, UserRound } from "lucide-react";
import api from "../../services/api";
import { readStoredUser } from "../auth/roleRouting";

type OrderItem = { id: string; quantity: number; price: number; menu_item?: { name?: string; image_url?: string }; addons?: { id: string; name_snapshot: string; quantity: number; price_snapshot: number }[] };
type OrderDetail = { id: string; status: string; created_at?: string; updated_at?: string; scheduled_time?: string; accepted_at?: string; preparing_at?: string; picked_up_at?: string; completed_at?: string; restaurant_order_code?: string; customer_name?: string; customer_phone?: string; user_id?: string; delivery_address?: string; apartment?: string; landmark?: string; delivery_type?: string; payment_method?: string; rider_arrived_at?: string; cancellation_reason?: string; failure_reason?: string; special_instructions?: string; total_amount?: number; delivery_fee?: number; additional_fees?: number; discount_amount?: number; order_subtotal?: number; vendor_commission_percentage?: number; vendor_commission_amount?: number; vendor_payout_amount?: number; rider_info?: { name?: string; phone?: string; vehicle_type?: string; profile_image?: string; user_id?: string }; order_items?: OrderItem[] };
type VendorProfile = { id: string; business_name?: string; bank_name?: string; bank_code?: string; account_number?: string; account_name?: string };
type Bank = { name: string; code: string };

const errorText = (error: unknown) => (error as { response?: { data?: { detail?: string } } }).response?.data?.detail || "Something went wrong. Please try again.";
const money = (value?: number) => `₦${Number(value || 0).toLocaleString("en-NG", { maximumFractionDigits: 2 })}`;
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());

export function VendorOrderDetail() {
  const { id = "" } = useParams();
  const [order, setOrder] = useState<OrderDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [pickupCode, setPickupCode] = useState(""); const [scannerOpen, setScannerOpen] = useState(false); const [scanError, setScanError] = useState("");
  const [now, setNow] = useState(Date.now());
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const { data } = await api.get<OrderDetail>(`/orders/${id}`); setOrder(data); } catch (err) { setError(errorText(err)); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const update = async (status: string, code?: string) => { setBusy(true); setError(""); try { if (status === "accepted") await api.post(`/orders/${id}/accept`); else if (status === "picked_up") await api.post(`/orders/${id}/verify-rider-pickup`, null, { params: { pickup_code: code } }); else await api.patch(`/orders/${id}/status`, null, { params: { status } }); setPickupCode(""); closeScanner(); await load(); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } };
  const closeScanner = () => { streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; setScannerOpen(false); };
  useEffect(() => () => streamRef.current?.getTracks().forEach(track => track.stop()), []);
  const openScanner = async () => {
    setScanError("");
    const Detector = (window as unknown as { BarcodeDetector?: new (options: { formats: string[] }) => { detect: (source: HTMLVideoElement) => Promise<{ rawValue: string }[]> } }).BarcodeDetector;
    if (!Detector || !navigator.mediaDevices?.getUserMedia) { setScanError("QR scanning is not supported in this browser. Enter the rider code instead."); return; }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }); streamRef.current = stream; setScannerOpen(true);
      window.setTimeout(async () => { const video = videoRef.current; if (!video) return; video.srcObject = stream; await video.play(); const detector = new Detector({ formats: ["qr_code"] }); const scan = async () => { if (!streamRef.current || !videoRef.current) return; try { const codes = await detector.detect(videoRef.current); if (codes[0]?.rawValue) { const raw = codes[0].rawValue; let code = raw; try { const parsed = JSON.parse(raw) as { rider_pickup_code?: string; pickup_code?: string; code?: string }; code = parsed.rider_pickup_code || parsed.pickup_code || parsed.code || raw; } catch { /* plain code */ } setPickupCode(code.trim().toUpperCase()); closeScanner(); } else requestAnimationFrame(scan); } catch { requestAnimationFrame(scan); } }; void scan(); }, 100);
    } catch { setScanError("Camera access was not granted. Enter the rider code instead."); closeScanner(); }
  };
  if (loading) return <div className="pepi-loading-grid" role="status"><span/><span/><span/></div>;
  if (error && !order) return <div className="pepi-state-card"><div><strong>Could not load this order</strong><p>{error}</p></div><button onClick={() => void load()}>Try again</button></div>;
  if (!order) return null;
  const placed = new Date(order.scheduled_time || order.created_at || 0).toLocaleString("en-NG", { dateStyle: "medium", timeStyle: "short" });
  const elapsedSeconds = Math.max(0, Math.floor((now - new Date(order.created_at || now).getTime()) / 1000));
  const elapsed = `${String(Math.floor(elapsedSeconds / 60)).padStart(2, "0")}:${String(elapsedSeconds % 60).padStart(2, "0")}`;
  const timeline = [{ label: "Order placed", at: order.created_at }, { label: "Kitchen accepted", at: order.accepted_at }, { label: "Preparation started", at: order.preparing_at }, { label: "Rider picked up", at: order.picked_up_at }, { label: "Completed", at: order.completed_at }];
  return <div className="pepi-vendor-detail">
    <div className="pepi-detail-top"><Link to="/vendor/orders"><ArrowLeft size={17}/>Back to orders</Link><span className={`pepi-status-badge status-${order.status}`}>{titleCase(order.status)}</span></div>
    <div className="pepi-dashboard-heading"><div><h2>Order {order.restaurant_order_code || `#${order.id.slice(0, 8).toUpperCase()}`}</h2><p>{order.scheduled_time ? `Scheduled for ${placed}` : `Placed ${placed} · Active for ${elapsed}`}</p></div><button className="pepi-secondary-action" onClick={() => void load()}>Refresh</button></div>
    {error && <div className="pepi-inline-error" role="alert">{error}</div>}
    {(order.cancellation_reason || order.failure_reason) && <div className="pepi-inline-error" role="alert"><strong>{order.status === "cancelled" ? "Cancellation reason:" : "Failure reason:"}</strong> {order.cancellation_reason || order.failure_reason}</div>}
    <div className="pepi-detail-layout"><div className="pepi-detail-primary">
      <section className="pepi-dashboard-card"><div className="pepi-card-heading"><div><h3>Order items</h3><p>{order.order_items?.length || 0} line items</p></div><Package size={19}/></div><div className="pepi-detail-items">{order.order_items?.map(item => <div key={item.id}>{item.menu_item?.image_url ? <img src={item.menu_item.image_url} alt=""/> : <span><Package size={18}/></span>}<p><strong>{item.quantity} × {item.menu_item?.name || "Meal"}</strong><small>{money(item.price)} each</small>{item.addons?.map(addon => <small key={addon.id}>+ {addon.quantity} × {addon.name_snapshot}</small>)}</p><b>{money(Number(item.price || 0) * item.quantity)}</b></div>)}</div></section>
      <section className="pepi-dashboard-card"><div className="pepi-card-heading"><div><h3>Customer and fulfilment</h3><p>{order.delivery_type === "pickup" ? "Customer pickup" : "Delivery"} · {order.payment_method === "cod" ? "Cash on delivery" : order.payment_method === "wallet" ? "Wallet" : "Paid online"}</p></div><UserRound size={19}/></div><div className="pepi-detail-contacts"><div><span><UserRound size={17}/></span><p><small>Customer</small><strong>{order.customer_name || "Customer"}</strong></p>{order.customer_phone && <a href={`tel:${order.customer_phone}`} aria-label="Call customer"><Phone size={17}/></a>}</div><div><span><MapPin size={17}/></span><p><small>{order.delivery_type === "pickup" ? "Fulfilment" : "Delivery address"}</small><strong>{order.delivery_type === "pickup" ? "Customer will collect this order" : order.delivery_address || "No address provided"}</strong>{(order.apartment || order.landmark) && <em>{[order.apartment, order.landmark].filter(Boolean).join(" · ")}</em>}</p></div>{order.delivery_type !== "pickup" && <div><span><Bike size={17}/></span><p><small>Rider</small><strong>{order.rider_info?.name || "Waiting for rider assignment"}</strong>{order.rider_info?.vehicle_type && <em>{order.rider_info.vehicle_type}</em>}{order.rider_arrived_at && <em>Arrived {new Date(order.rider_arrived_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</em>}</p>{order.rider_info?.phone && <a href={`tel:${order.rider_info.phone}`} aria-label="Call rider"><Phone size={17}/></a>}</div>}</div><div className="pepi-action-row">{order.user_id && <Link className="pepi-secondary-action" to={`/vendor/chat?recipientId=${encodeURIComponent(order.user_id)}`}><MessageCircle size={16}/>Message customer</Link>}{order.rider_info?.user_id && <Link className="pepi-secondary-action" to={`/vendor/chat?recipientId=${encodeURIComponent(order.rider_info.user_id)}`}><MessageCircle size={16}/>Message rider</Link>}</div></section>
      <section className="pepi-instruction-card"><strong>Special instructions</strong><p>{order.special_instructions || "No special instructions were added to this order."}</p></section>
      <section className="pepi-dashboard-card"><div className="pepi-card-heading"><div><h3>Order progress</h3><p>Recorded activity for this order</p></div><Clock3 size={19}/></div><div className="pepi-order-timeline">{timeline.map((step, index) => <div className={step.at ? "complete" : ""} key={step.label}><i>{step.at ? <CheckCircle2 size={13}/> : index + 1}</i><span><strong>{step.label}</strong><small>{step.at ? new Date(step.at).toLocaleString("en-NG", { dateStyle: "medium", timeStyle: "short" }) : "Waiting"}</small></span></div>)}</div></section>
    </div><aside className="pepi-detail-sidebar">
      <section className="pepi-dashboard-card pepi-financial-card"><h3>Order summary</h3><p><span>Subtotal</span><strong>{money(order.order_subtotal)}</strong></p>{Boolean(order.discount_amount) && <p><span>Discount</span><strong>-{money(order.discount_amount)}</strong></p>}{Boolean(order.additional_fees) && <p><span>Additional fees</span><strong>{money(order.additional_fees)}</strong></p>}<p><span>Delivery fee</span><strong>{money(order.delivery_fee)}</strong></p><p><span>Customer total</span><strong>{money(order.total_amount)}</strong></p><p><span>Platform commission {order.vendor_commission_percentage ? `(${order.vendor_commission_percentage}%)` : ""}</span><strong>-{money(order.vendor_commission_amount)}</strong></p><div><span>Your payout</span><strong>{money(order.vendor_payout_amount)}</strong></div></section>
      <section className="pepi-dashboard-card pepi-order-next"><h3>Next action</h3>{order.status === "pending" && <><button disabled={busy} className="pepi-primary" onClick={() => void update("accepted")}>Accept order</button><button disabled={busy} onClick={() => void update("cancelled")}>Decline order</button></>}{["confirmed", "accepted", "preparing"].includes(order.status) && <button disabled={busy} className="pepi-primary" onClick={() => void update("ready")}>Mark ready for pickup</button>}{order.status === "ready" && <><label>Rider pickup code<input value={pickupCode} onChange={event => setPickupCode(event.target.value.toUpperCase())} placeholder="Enter rider code"/></label><button type="button" className="pepi-scan-button" onClick={() => void openScanner()}><Camera size={17}/>Scan QR code</button><button disabled={busy || !pickupCode.trim()} className="pepi-primary" onClick={() => void update("picked_up", pickupCode)}>Confirm rider pickup</button>{scanError && <p role="status">{scanError}</p>}</>}{["picked_up", "completed", "cancelled"].includes(order.status) && <div className="pepi-complete-state"><CheckCircle2 size={25}/><strong>{titleCase(order.status)}</strong><p>No further kitchen action is required.</p></div>}</section>
    </aside></div>
    {scannerOpen && <div className="pepi-dialog-backdrop"><section className="pepi-dialog pepi-scanner"><h3>Scan rider QR code</h3><p>Place the rider code inside the camera frame.</p><video ref={videoRef} playsInline muted/><button onClick={closeScanner}>Cancel scanning</button></section></div>}
  </div>;
}

export function VendorPaymentSettings() {
  const vendorId = readStoredUser()?.vendor_id || "";
  const [profile, setProfile] = useState<VendorProfile | null>(null); const [banks, setBanks] = useState<Bank[]>([]); const [bankSearch, setBankSearch] = useState(""); const [bankOpen, setBankOpen] = useState(false); const [bankName, setBankName] = useState(""); const [bankCode, setBankCode] = useState(""); const [accountNumber, setAccountNumber] = useState(""); const [accountName, setAccountName] = useState(""); const [resolving, setResolving] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { api.get<VendorProfile>(`/vendors/${vendorId}`).then(({ data }) => { setProfile(data); setBankName(data.bank_name || ""); setBankCode(data.bank_code || ""); setAccountNumber(data.account_number || ""); setAccountName(data.account_name || ""); }).catch(err => setMessage(errorText(err))); api.get<{ data?: Bank[] } | Bank[]>("/system/banks").then(({ data }) => setBanks(Array.isArray(data) ? data : data.data || [])).catch(() => setMessage("Could not load the bank list.")); }, [vendorId]);
  useEffect(() => { if (accountNumber.length !== 10 || !bankCode) { if (accountNumber !== profile?.account_number) setAccountName(""); return; } const timer = window.setTimeout(async () => { setResolving(true); setMessage(""); try { const { data } = await api.get<{ data?: { account_name?: string } }>("/system/resolve-account", { params: { account_number: accountNumber, bank_code: bankCode } }); setAccountName(data.data?.account_name || ""); if (!data.data?.account_name) setMessage("The account name could not be verified."); } catch (err) { setAccountName(""); setMessage(errorText(err)); } finally { setResolving(false); } }, 450); return () => window.clearTimeout(timer); }, [accountNumber, bankCode, profile?.account_number]);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); try { await api.patch(`/vendors/${vendorId}`, { bank_name: bankName, bank_code: bankCode, account_number: accountNumber, account_name: accountName }); setMessage("Payment information saved."); } catch (err) { setMessage(errorText(err)); } finally { setSaving(false); } };
  const filtered = banks.filter(bank => bank.name.toLowerCase().includes(bankSearch.toLowerCase()));
  return <div className="pepi-settings-page"><div className="pepi-dashboard-heading"><div><h2>Payment information</h2><p>Manage the verified bank account used for vendor payouts.</p></div></div><form className="pepi-dashboard-card pepi-settings-form" onSubmit={save}><label>Bank<button type="button" className="pepi-select-button" onClick={() => setBankOpen(true)}>{bankName || "Choose a bank"}<ChevronRight size={16}/></button></label><label>Account number<input inputMode="numeric" maxLength={10} value={accountNumber} onChange={event => setAccountNumber(event.target.value.replace(/\D/g, ""))} placeholder="10-digit account number" required/></label><label>Verified account name<input value={resolving ? "Verifying account" : accountName} readOnly placeholder="Account name appears after verification" required/></label><button className="pepi-primary" disabled={saving || resolving || !accountName}>{saving ? "Saving" : "Save payment information"}</button>{message && <div className={message.includes("saved") ? "pepi-inline-notice" : "pepi-inline-error"}>{message}</div>}</form>{bankOpen && <div className="pepi-dialog-backdrop" onMouseDown={() => setBankOpen(false)}><section className="pepi-dialog pepi-bank-dialog" onMouseDown={event => event.stopPropagation()}><h3>Select a bank</h3><input autoFocus value={bankSearch} onChange={event => setBankSearch(event.target.value)} placeholder="Search banks"/><div>{filtered.map(bank => <button key={bank.code} onClick={() => { setBankName(bank.name); setBankCode(bank.code); setBankOpen(false); setBankSearch(""); setAccountName(""); }}>{bank.name}{bank.code === bankCode && <CheckCircle2 size={16}/>}</button>)}</div><button onClick={() => setBankOpen(false)}>Close</button></section></div>}</div>;
}

export function VendorPasswordSettings() {
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); if (newPassword !== confirm) { setMessage("New passwords do not match."); return; } setBusy(true); setMessage(""); try { await api.post("/vendors/change-password", { current_password: currentPassword, new_password: newPassword }); setCurrentPassword(""); setNewPassword(""); setConfirm(""); setMessage("Password changed successfully."); } catch (err) { setMessage(errorText(err)); } finally { setBusy(false); } };
  return <div className="pepi-settings-page"><div className="pepi-dashboard-heading"><div><h2>Change password</h2><p>Use a unique password that you do not use anywhere else.</p></div></div><form className="pepi-dashboard-card pepi-settings-form" onSubmit={submit}><label>Current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} required/></label><label>New password<input type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={event => setNewPassword(event.target.value)} required/><small>Use at least eight characters.</small></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength={8} value={confirm} onChange={event => setConfirm(event.target.value)} required/></label><button className="pepi-primary" disabled={busy}>{busy ? "Updating" : "Update password"}</button>{message && <div className={message.includes("successfully") ? "pepi-inline-notice" : "pepi-inline-error"}>{message}</div>}</form></div>;
}

export function VendorSettings() {
  const navigate = useNavigate(); const [confirming, setConfirming] = useState(false); const [confirmation, setConfirmation] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const remove = async () => { setBusy(true); setError(""); try { await api.delete("/vendors/account"); localStorage.clear(); navigate("/", { replace: true }); } catch (err) { setError(errorText(err)); setBusy(false); } };
  const links = [{ to: "/vendor/profile/edit", icon: Store, title: "Business profile", text: "Name, address, contact details, and kitchen information" }, { to: "/vendor/payment-settings", icon: CreditCard, title: "Payment information", text: "Verified bank account and payout readiness" }, { to: "/vendor/change-password", icon: LockKeyhole, title: "Password", text: "Update your sign-in password" }, { to: "/vendor/profile/sessions", icon: Shield, title: "Devices and sessions", text: "Review where your account is signed in" }, { to: "/vendor/notifications", icon: MessageCircle, title: "Notifications", text: "Order, payout, and account updates" }];
  return <div className="pepi-settings-page"><div className="pepi-dashboard-heading"><div><h2>Vendor settings</h2><p>Manage your kitchen account, security, payments, and legal information.</p></div></div><div className="pepi-settings-links">{links.map(({ to, icon: Icon, title, text }) => <Link to={to} key={to}><span><Icon size={19}/></span><p><strong>{title}</strong><small>{text}</small></p><ChevronRight size={17}/></Link>)}</div><section className="pepi-dashboard-card pepi-legal-links"><h3>Legal and support</h3><Link to="/privacy"><Shield size={17}/>Privacy policy<ChevronRight size={16}/></Link><Link to="/terms"><FileText size={17}/>Terms of service<ChevronRight size={16}/></Link><Link to="/vendor/support"><MessageCircle size={17}/>Contact support<ChevronRight size={16}/></Link></section><section className="pepi-danger-zone"><div><Trash2 size={20}/><span><strong>Delete vendor account</strong><p>Permanently remove your vendor profile and account data.</p></span></div><button onClick={() => setConfirming(true)}>Delete account</button></section>{error && <div className="pepi-inline-error">{error}</div>}{confirming && <div className="pepi-dialog-backdrop" onMouseDown={() => setConfirming(false)}><section className="pepi-dialog" onMouseDown={event => event.stopPropagation()}><h3>Delete your vendor account?</h3><p>This action cannot be undone. Type DELETE to confirm permanent deletion.</p><label>Confirmation<input autoFocus value={confirmation} onChange={event => setConfirmation(event.target.value)} placeholder="Type DELETE"/></label><div className="pepi-dialog-actions"><button onClick={() => setConfirming(false)}>Cancel</button><button disabled={busy || confirmation !== "DELETE"} onClick={() => void remove()}>{busy ? "Deleting" : "Delete permanently"}</button></div></section></div>}</div>;
}
