/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from "react";
import { Loader2, Plus, RefreshCw, X } from "lucide-react";
import api from "../../services/api";
import { useToast } from "../../context/ToastContext";

const field = "w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:ring-2 focus:ring-green-500";
const emptyIssue = { subject_type: "customer", subject_id: "", category: "", summary: "", severity: "medium" };
const emptyCase = { kind: "dispute", order_id: "", user_id: "", amount: "0", reason: "" };

export default function OperationsAttention() {
  const toast = useToast();
  const [issues, setIssues] = useState<any[]>([]); const [records, setRecords] = useState<any[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [formType, setFormType] = useState<"issue" | "case" | null>(null);
  const [issue, setIssue] = useState(emptyIssue); const [financialCase, setFinancialCase] = useState(emptyCase);
  const load = async () => { setLoading(true); try { const [a, b] = await Promise.all([api.get("/admin/issues"), api.get("/admin/refund-disputes")]); setIssues(a.data || []); setRecords(b.data || []); } catch { toast.error("Failed to load attention queues"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const change = async (path: string, status: string) => { try { await api.patch(path, { status }); toast.success("Status updated"); await load(); } catch (error: any) { toast.error(error.response?.data?.detail || "Update failed"); } };
  const createIssue = async () => { if (issue.category.trim().length < 3 || issue.summary.trim().length < 3) return toast.error("Category and summary required"); setBusy(true); try { await api.post("/admin/issues", { ...issue, subject_id: issue.subject_id.trim() || null, category: issue.category.trim(), summary: issue.summary.trim() }); toast.success("Issue created"); setIssue(emptyIssue); setFormType(null); await load(); } catch (error: any) { toast.error(error.response?.data?.detail || "Create failed"); } finally { setBusy(false); } };
  const createCase = async () => { const amount = Number(financialCase.amount); if (financialCase.kind === "refund" && (!financialCase.order_id.trim() || amount <= 0)) return toast.error("Refund needs order ID and amount"); if (financialCase.reason.trim().length < 3) return toast.error("Reason required"); setBusy(true); try { await api.post("/admin/refund-disputes", { kind: financialCase.kind, order_id: financialCase.order_id.trim() || null, user_id: financialCase.user_id.trim() || null, amount, reason: financialCase.reason.trim() }); toast.success(financialCase.kind === "refund" ? "Provider refund submitted" : "Dispute logged"); setFinancialCase(emptyCase); setFormType(null); await load(); } catch (error: any) { toast.error(error.response?.data?.detail || "Create failed"); } finally { setBusy(false); } };
  if (loading) return <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-green-600"/></div>;
  return <section className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-green-600">Operations queues</p><h1 className="text-2xl font-black">Issues, refunds and disputes</h1><p className="mt-1 text-sm text-slate-500">Refund actions contact payment provider; statuses stay webhook-controlled.</p></div><div className="flex gap-2"><button onClick={() => setFormType("issue")} className="flex items-center gap-2 rounded-xl bg-amber-100 px-4 py-3 text-xs font-black text-amber-900"><Plus size={15}/>Log issue</button><button onClick={() => setFormType("case")} className="flex items-center gap-2 rounded-xl bg-violet-100 px-4 py-3 text-xs font-black text-violet-900"><Plus size={15}/>Refund / dispute</button><button onClick={load} className="rounded-xl bg-white p-3 shadow-sm"><RefreshCw size={18}/></button></div></div>
  {formType && <div className="rounded-3xl border border-green-100 bg-green-50 p-5"><div className="flex justify-between"><h2 className="font-black">{formType === "issue" ? "New operations issue" : "New refund or dispute"}</h2><button onClick={() => setFormType(null)}><X size={18}/></button></div>{formType === "issue" ? <div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={issue.subject_type} onChange={event => setIssue(current => ({ ...current, subject_type: event.target.value }))} className={field}>{["customer","vendor","rider","order"].map(value => <option key={value}>{value}</option>)}</select><input value={issue.subject_id} onChange={event => setIssue(current => ({ ...current, subject_id: event.target.value }))} placeholder="Subject UUID (optional)" className={field}/><input value={issue.category} onChange={event => setIssue(current => ({ ...current, category: event.target.value }))} placeholder="Category" className={field}/><select value={issue.severity} onChange={event => setIssue(current => ({ ...current, severity: event.target.value }))} className={field}>{["low","medium","high","critical"].map(value => <option key={value}>{value}</option>)}</select><textarea value={issue.summary} onChange={event => setIssue(current => ({ ...current, summary: event.target.value }))} placeholder="Issue summary" className={`${field} min-h-24 sm:col-span-2`}/><button disabled={busy} onClick={createIssue} className="rounded-xl bg-green-700 p-3 text-xs font-black text-white sm:col-span-2">Create issue</button></div> : <div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={financialCase.kind} onChange={event => setFinancialCase(current => ({ ...current, kind: event.target.value }))} className={field}><option value="dispute">Dispute case</option><option value="refund">Execute refund</option></select><input type="number" min="0" step="0.01" value={financialCase.amount} onChange={event => setFinancialCase(current => ({ ...current, amount: event.target.value }))} placeholder="Amount" className={field}/><input value={financialCase.order_id} onChange={event => setFinancialCase(current => ({ ...current, order_id: event.target.value }))} placeholder="Order UUID (required for refund)" className={field}/><input value={financialCase.user_id} onChange={event => setFinancialCase(current => ({ ...current, user_id: event.target.value }))} placeholder="Customer UUID (optional)" className={field}/><textarea value={financialCase.reason} onChange={event => setFinancialCase(current => ({ ...current, reason: event.target.value }))} placeholder="Reason" className={`${field} min-h-24 sm:col-span-2`}/><button disabled={busy} onClick={createCase} className="rounded-xl bg-violet-700 p-3 text-xs font-black text-white sm:col-span-2">{financialCase.kind === "refund" ? "Submit provider refund" : "Log dispute"}</button></div>}</div>}
  <div className="grid gap-5 xl:grid-cols-2"><Queue title="Issues requiring attention" rows={issues} render={(row: any) => <><p className="text-xs font-black uppercase text-amber-700">{row.subject_type} · {row.category} · {row.severity}</p><p className="mt-1 text-sm">{row.summary}</p><Actions status={row.status} onChange={(status: string) => change(`/admin/issues/${row.id}`, status)} options={["open","in_progress","resolved"]}/></>}/><Queue title="Refunds and disputes" rows={records} render={(row: any) => <><p className="text-xs font-black uppercase text-violet-700">{row.kind} · ₦{Number(row.amount || 0).toLocaleString()} · {row.provider || "manual case"}</p><p className="mt-1 text-sm">{row.reason || "No reason recorded"}</p>{row.failure_reason && <p className="mt-2 rounded-lg bg-red-50 p-2 text-xs font-bold text-red-700">{row.failure_reason}</p>}{row.kind === "refund" && row.provider ? <p className="mt-3 text-[10px] font-black uppercase text-slate-400">Provider status: {row.status}</p> : <Actions status={row.status} onChange={(status: string) => change(`/admin/refund-disputes/${row.id}`, status)} options={["open","pending","approved","rejected","resolved"]}/>}</>}/></div></section>;
}
function Queue({ title, rows, render }: any) { return <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="font-black">{title}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black">{rows.length}</span></div><div className="mt-4 space-y-3">{rows.length ? rows.map((row: any) => <article key={row.id} className="rounded-2xl bg-slate-50 p-4">{render(row)}</article>) : <p className="py-10 text-center text-sm text-slate-400">Queue clear</p>}</div></section>; }
function Actions({ status, onChange, options }: any) { return <div className="mt-3 flex items-center gap-2"><span className="text-[10px] font-black uppercase text-slate-400">Current: {status}</span><select value={status} onChange={event => onChange(event.target.value)} className="ml-auto rounded-xl bg-white px-3 py-2 text-xs font-black">{options.map((value: string) => <option key={value}>{value}</option>)}</select></div>; }
