/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Loader2, Search, ShieldAlert, Wallet } from "lucide-react";
import api from "../../services/api";
import { useToast } from "../../context/ToastContext";

const money = (value: unknown) => `₦${Number(value || 0).toLocaleString()}`;
const date = (value: string) => value ? new Date(value).toLocaleString() : "—";

export default function UserManagement() {
  const toast = useToast();
  const [users, setUsers] = useState<any[]>([]);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<any>(null);
  const [profile, setProfile] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState<any>({});
  const [walletForm, setWalletForm] = useState({ amount: "", reason: "" });
  const [showWallet, setShowWallet] = useState(false);

  const load = async () => { setLoading(true); try { const { data } = await api.get("/admin/users"); setUsers((data || []).filter((u: any) => (u.role || "customer") === "customer")); } catch { toast.error("Failed to load customers"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const open = async (user: any) => { setSelected(user); setProfile(null); try { const { data } = await api.get(`/admin/users/${user.id}/profile`); setProfile(data); setForm(data.customer); } catch { toast.error("Failed to load customer profile"); } };
  const update = async (values: any, message: string) => { if (!selected) return; setBusy(true); try { await api.patch(`/admin/users/${selected.id}`, values); toast.success(message); await open(selected); await load(); } catch (error: any) { toast.error(error.response?.data?.detail || "Action failed"); } finally { setBusy(false); } };
  const adjustWallet = async () => { const amount = Number(walletForm.amount); const reason = walletForm.reason.trim(); if (!Number.isFinite(amount) || amount === 0 || reason.length < 5) return toast.error("Enter a non-zero amount and clear reason"); setBusy(true); try { await api.post(`/admin/users/${selected.id}/wallet`, { amount, reason }); toast.success("Wallet updated"); setWalletForm({ amount: "", reason: "" }); setShowWallet(false); await open(selected); } catch (error: any) { toast.error(error.response?.data?.detail || "Wallet update failed"); } finally { setBusy(false); } };
  const save = async () => { await update({ firstname: form.firstname, lastname: form.lastname, email: form.email, phone: form.phone, address: form.address, city: form.city, state: form.state, zip: form.zip }, "Customer updated"); setEditing(false); };
  const filtered = useMemo(() => users.filter((u) => `${u.firstname || ""} ${u.lastname || ""} ${u.email || ""} ${u.phone || ""}`.toLowerCase().includes(query.toLowerCase())), [users, query]);

  if (selected) return <section className="space-y-4"><button onClick={() => { setSelected(null); setProfile(null); }} className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-black shadow-sm"><ArrowLeft size={17}/> Customers</button>{!profile ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-green-600"/></div> : <>
    <header className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-green-400">Customer profile</p><h1 className="mt-1 text-2xl font-black">{profile.customer.firstname} {profile.customer.lastname}</h1><p className="text-sm text-slate-400">{profile.customer.email} · {profile.customer.phone || "No phone"}</p>{profile.customer.referral_code && <p className="mt-2 text-xs font-black text-green-300">Referral code: {profile.customer.referral_code}</p>}</div><div className="flex flex-wrap gap-2">{profile.customer.is_suspicious && <span className="rounded-full bg-red-500/20 px-3 py-2 text-xs font-black text-red-300">Flagged</span>}<span className={`rounded-full px-3 py-2 text-xs font-black ${profile.customer.is_active ? "bg-green-500/20 text-green-300" : "bg-red-500/20 text-red-300"}`}>{profile.customer.is_active ? "Active" : "Suspended"}</span></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Joined", date(profile.customer.created_at)], ["Spent", money(profile.total_spending)], ["Wallet", money(profile.customer.balance)], ["Orders", profile.orders.length]].map(([label, value]) => <div key={String(label)} className="rounded-2xl bg-white/10 p-3"><p className="text-lg font-black">{value}</p><p className="text-[10px] uppercase text-slate-400">{label}</p></div>)}</div></header>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><button disabled={busy} onClick={() => update({ is_active: !profile.customer.is_active }, profile.customer.is_active ? "Customer suspended" : "Customer restored")} className="rounded-xl bg-amber-50 p-3 text-xs font-black text-amber-800">{profile.customer.is_active ? "Suspend" : "Unsuspend"}</button><button disabled={busy} onClick={() => update({ is_verified: true }, "Customer verified")} className="rounded-xl bg-green-50 p-3 text-xs font-black text-green-800">Verify</button><button disabled={busy} onClick={() => update({ is_suspicious: !profile.customer.is_suspicious }, "Risk flag updated")} className="rounded-xl bg-red-50 p-3 text-xs font-black text-red-800"><ShieldAlert className="mx-auto mb-1" size={16}/>Flag risk</button><button disabled={busy} onClick={() => setShowWallet(value => !value)} className="rounded-xl bg-blue-50 p-3 text-xs font-black text-blue-800"><Wallet className="mx-auto mb-1" size={16}/>Wallet credit</button><button disabled={busy} onClick={() => update({ promo_blocked: !profile.customer.promo_blocked }, "Promo access updated")} className="rounded-xl bg-violet-50 p-3 text-xs font-black text-violet-800">{profile.customer.promo_blocked ? "Allow promos" : "Block promo abuse"}</button><button onClick={() => setEditing(!editing)} className="rounded-xl bg-slate-100 p-3 text-xs font-black">Edit profile</button></div>
    {showWallet && <div className="grid gap-3 rounded-3xl border border-blue-100 bg-blue-50 p-5 sm:grid-cols-[180px_1fr_auto]"><label className="text-[10px] font-black uppercase text-blue-700">Amount<input type="number" step="0.01" value={walletForm.amount} onChange={event => setWalletForm(current => ({ ...current, amount: event.target.value }))} placeholder="+ adds, - removes" className="mt-1 w-full rounded-xl bg-white p-3 text-sm normal-case outline-none focus:ring-2 focus:ring-blue-500"/></label><label className="text-[10px] font-black uppercase text-blue-700">Audit reason<input value={walletForm.reason} onChange={event => setWalletForm(current => ({ ...current, reason: event.target.value }))} placeholder="Why this balance changes" className="mt-1 w-full rounded-xl bg-white p-3 text-sm normal-case outline-none focus:ring-2 focus:ring-blue-500"/></label><button disabled={busy} onClick={adjustWallet} className="self-end rounded-xl bg-blue-700 px-5 py-3 text-xs font-black text-white disabled:opacity-50">Apply</button></div>}
    {editing && <div className="grid gap-3 rounded-3xl bg-white p-5 shadow-sm sm:grid-cols-2">{["firstname","lastname","email","phone","address","city","state","zip"].map(key => <label key={key} className={key === "address" ? "sm:col-span-2" : ""}><span className="text-[10px] font-black uppercase text-slate-400">{key}</span><input value={form[key] || ""} onChange={e => setForm({...form, [key]: e.target.value})} className="mt-1 w-full rounded-xl bg-slate-50 p-3 text-sm outline-none focus:ring-2 focus:ring-green-500"/></label>)}<button disabled={busy} onClick={save} className="rounded-xl bg-green-600 p-3 text-sm font-black text-white sm:col-span-2">Save changes</button></div>}
    <div className="grid gap-4 xl:grid-cols-2"><Data title="Saved addresses" rows={profile.addresses} fields={["address_name","address","delivery_instructions"]}/><Data title="Order history" rows={profile.orders} fields={["restaurant_name","status","total_amount","cancellation_reason","created_at"]}/><Data title="Payment history" rows={profile.payments} fields={["status","amount","payment_method","paystack_reference","created_at"]}/><Data title="Favourite vendors" rows={profile.favorite_vendors} fields={["business_name","business_email","status"]}/><Data title="Promo history" rows={profile.promo_history} fields={["promo_code_id","discount_amount","created_at"]}/><Data title="Referral history" rows={profile.referral_history} fields={["direction","name","email","created_at"]}/><Data title="Refunds and disputes" rows={profile.refunds} fields={["kind","amount","status","reason"]}/><Data title="Support tickets" rows={profile.support_tickets} fields={["ticket_number","category","priority","status","subject","created_at"]}/><Data title="Operations issues" rows={profile.issues} fields={["category","severity","status","summary"]}/><Data title="Ratings and reviews" rows={profile.reviews} fields={["rating","comment","created_at"]}/><Data title="Devices and sessions" rows={profile.sessions} fields={["device_name","platform","ip_address","last_active","is_active"]}/><Data title="Admin account activity" rows={profile.activity} fields={["action","details","created_at"]}/></div>
  </>}</section>;

  return <section className="space-y-5"><div><p className="text-xs font-black uppercase text-green-600">Customer operations</p><h1 className="text-2xl font-black">Customers</h1></div><label className="relative block"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, email or phone" className="w-full rounded-2xl bg-white py-4 pl-12 pr-4 shadow-sm outline-none focus:ring-2 focus:ring-green-500"/></label>{loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-green-600"/></div> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(user => <button key={user.id} onClick={() => open(user)} className="rounded-2xl bg-white p-5 text-left shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-black">{user.firstname} {user.lastname}</h2><p className="text-sm text-slate-500">{user.email}</p><p className="text-xs text-slate-400">{user.phone}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[10px] font-black ${user.is_active === false ? "bg-red-50 text-red-700" : "bg-green-50 text-green-700"}`}>{user.is_active === false ? "Suspended" : "Active"}</span></div></button>)}</div>}</section>;
}

function Data({ title, rows = [], fields }: { title: string; rows: any[]; fields: string[] }) { return <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">{title}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-black">{rows.length}</span></div><div className="mt-4 max-h-80 space-y-2 overflow-auto">{rows.length ? rows.map((row, index) => <div key={row.id || index} className="rounded-2xl bg-slate-50 p-3">{fields.map(field => row[field] !== null && row[field] !== undefined && row[field] !== "" ? <p key={field} className="break-words text-xs text-slate-600"><span className="font-black capitalize">{field.replaceAll("_", " ")}: </span>{typeof row[field] === "object" ? JSON.stringify(row[field]) : field.includes("amount") || field === "total_amount" ? money(row[field]) : field.includes("_at") ? date(row[field]) : String(row[field])}</p> : null)}</div>) : <p className="py-6 text-center text-sm text-slate-400">None recorded</p>}</div></section>; }
